#ifndef included_587DD57A_CD2F_4580_81C6_EC13D0764C6
#define included_587DD57A_CD2F_4580_81C6_EC13D0764C6

#include "gtest/gtest.h"

#define ASSERT_EQUALS ASSERT_EQ
#define ASSERT_NOT_EQUALS ASSERT_NE
#define ASSERT_APPROX_EQUAL ASSERT_NEAR
#define ASSERT_OK(EXPRESSION) ASSERT_EQUALS(::mongo::Status::OK(), (EXPRESSION))
#define ASSERT_NOT_OK(EXPRESSION) ASSERT_NOT_EQUALS(::mongo::Status::OK(), (EXPRESSION))

#endif
